### ISSUE TITLE
Can't remove single Block elevator.

### ISSUE THREAD

**Issue by trainsa** [Thutmose/Thut#138]
It seems to be unpossible to remove an elevator that is just a single block high an wide.

**Comment by Thutmose** [comment]
did you try shift right clicking it with a stick? you might need to remove surrounding blocks to access it

**Comment by SystemtechCA** [comment]
We have this issue on our server too. I just updated to ThutCore 5.20.2 to try fix it but that did not help.
Given that we just had a few elevator blocks(just starting to make elevators) we removed the mods from the server, and the re-added them after a reboot, which removed all the Thut blocks from the world.

To reproduce the issue, get the device linker, Shift-left-click the first corner of your elevator, Shift-left-click the second and get the message : Elevator Created. 
Then Shift-left-click the control block, and it will go all grey and be invincible.
![broken evelavtor](https://user-images.githubusercontent.com/29926065/57717895-2ca24400-764a-11e9-96b7-b56a10cfbfb6.jpeg)

In the image, the right block works as expected, the left block is invincible and invalid. Cannot be removed/altered or anything.

I believe this is because when you create the elevator floor, you need to Shift-Left-Click a third time to link it to the controller. If you don't do the third click, its tries to make an elevator out of the controller but cannot be broken.

Minecraft : 1.12.2
Forge version : 14.23.5.2824
Thutcore : 5.20.2
Thuttech : 6.1.5

**Comment by Thutmose** [comment]
if you press f3+b, does it have a white outline around the block? also, can you shift right click it with a stick?

**Comment by SystemtechCA** [comment]
I can confirm that Shift+right-click does absolutely nothing. I have tried all 6 faces of the block.
And yes, there are white borders around the block
![Stuck Elevator](https://user-images.githubusercontent.com/29926065/57955616-59fa2680-78c4-11e9-9da6-6318d821393c.png)

**Comment by Thutmose** [comment]
Ok, I will definitely look into this then, I suspect the custom code for dealing with the controller is interfering with the code that kills it

**Comment by SystemtechCA** [comment]
Thank you.
