### ISSUE TITLE
[1.12] Mod Incompatibility w/ Colossal Chests

### ISSUE THREAD

**Issue by hextrace** [Thutmose/Thut#53]
There is a mod incompatibility with Thut's Elevators and Colossal Chests for Minecraft 1.12.  I've submitted the crash report with Rubensworks on their [GitHub](https://github.com/CyclopsMC/ColossalChests/issues/85).  Rubenswork suggested that I should also report this issue here as well - modified with updated information:

**Minecraft Version:** 1.12.0
**Forge Version:** xxx.2387
**Colossal Chests Version:** 1.6.2
**Cyclops Core Version:** 0.10.7
**Thut's Elevators Version:** 6.0.0.b
**ThutCore Version:** 5.0.1
**Crash Report:** https://paste.ee/p/2Mkfw

**Issue:**
Minecraft fails to load properly and crashes out.

**Details (Modified):**
The crash report is not very descriptive; however, when building a 1.12 modpack I had been adding mods 1x1.  Issue first presented itself after I had already installed Thut's Elevators and subsequently added Colossal Chests.  Testing showed that both mods will work independent of each other; however, when both are enabled Minecraft will crash on load.

**Comment by Thutmose** [comment]
Hmm, I will look into it, I will try to get this crash to occur without any core mods* installed, then I will see if I can get it to occur in my development environment, I suspect either I, or Colossal Chests is probably registering something at the wrong time, but it could be something else.

I will go through my registration stuff and see if I can find anything out of order.

*Actual core mods, rather than libs like thutcore and cyclops core

**Comment by Thutmose** [comment]
i confirmed that this crash occurs without any core mods installed, I will try to look and see what I do differently between thuttech and pokecube, since pokecube doesn't crash with Colossal Chests.

**Comment by Thutmose** [comment]
uploaded 6.0.1 which fixes this issue.
