### ISSUE TITLE
Elevator turns invisible + Falling through elevators

### ISSUE THREAD

**Issue by steampunko** [Thutmose/Thut#77]
So, I've built an elevator and whenever I try to activate it it turns invisible... Also when I try to stand on it I fall through yet I can't go back up through it

**Comment by Thutmose** [comment]
Can you send screenshots of the elevator you are trying to make?

**Comment by steampunko** [comment]
Can't get a photo of it right now, will have to download the map with the
elevator on it since the server that's running it is going through a reset

**Comment by steampunko** [comment]
Welp, it looks like I won't be getting a photo... They didn't backup the world before they reset. I'll try to reproduce it

**Comment by BladeBreaker** [comment]
I also have trouble with my elevators going invisible + I fall through.
It happens when I come out of the mining dimension via Aroma1997 Dimensional Worlds near the elevator in the Regular world.
Appears to be 100% repro so far.
The Elevator controls also act as if there is no elevator placed.
Also other players on the server COULD see the elevator & use it if they went to the elevator by normal means (not going through the Aroma1997 dimensional world) and I could watch them use it while I could not use it, nor see it.

**Comment by Thutmose** [comment]
Falling through should now be fixed.

There is one case of invisible elevators caused by a minecraft bug that I can't fix without asm, it is where elevators in certain locations go invisible from certain view angles
