### ISSUE TITLE
Crash when pressing floor button with no associated floor

### ISSUE THREAD

**Issue by oliverjrose99** [Thutmose/Thut#80]
I found that the game would crash when I press a floor button that has no floor linked to it. I have a controller with one set of buttons facing inwards to the lift and one facing outwards to the floor/room. It will crash when pressing a button on the set facing inwards but not on the set facing outwards. As stated it only crashes on floor buttons with no associated/linked floor.

MC 1.10.2
Forge 12.18.3.2511
Java 1.8.0

[Crash log](https://pastebin.com/bL7LXvzu)

**Comment by Thutmose** [comment]
Were you holding any item when you did that? I suspect this is related to the checks for placing items while standing on a lift

**Comment by oliverjrose99** [comment]
Crashed with:
- Empty Inventory
- Full Inventory with no item in hand
- Full inventory with item in hand

**Comment by oliverjrose99** [comment]
I also found it would crash when trying to place an item in the lift, even if there is no item in hand.

**Comment by Thutmose** [comment]
Hmm, I have made quite a few backend changes to the interaction code since I last uploaded updates for 1.10.2, I shall test to see if those errors still occur in my development environment, and if not, will see about updating my 1.10.2 mods (will take a bit, have to update the entire pokecube line as well if I update thutcore...)

**Comment by Thutmose** [comment]
cleaning up old issues for unsupported versions, no longer have time to go back and attempt to look at older version unfortunately
